name: Create and publish a release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Specify a version (e.g. 1.0.23)'
      prerelease:
        type: boolean
        default: false        
        description: 'Is this a pre-release version?'
        
permissions: write-all

jobs:
  example:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create & Push Release Tag
        run: |
          git tag "release-${{ github.event.inputs.version }}"
          git push origin --tags
          
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    name: ${{ github.event.inputs.version }}
      #    prerelease: ${{ github.event.inputs.prerelease }}
