name: Create and publish a release
on:
  workflow_dispatch:
    inputs:
      message:
        required: true
      
jobs:
  example:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
