name: Create and publish a release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Specify a version (e.g. 1.0.23)'
      prerelease:
        type: boolean
        default: false        
        description: 'Is this a pre-release version?'
      
jobs:
  example:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Create Release Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "release-${{ github.event.inputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Release
      #  uses: softprops/action-gh-release@v1
      #  with:
      #    name: ${{ github.event.inputs.version }}
      #    prerelease: ${{ github.event.inputs.prerelease }}
