name: Create and publish a release
on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
      
jobs:
  example:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
