name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      prerelease:
        type: boolean
        default: false
        
permissions: write-all

jobs:
  example:
    name: Create & Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create & Push Release Tag
        run: |
          git tag "release-${{ github.event.inputs.version }}"
          git push origin --tags
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
