name: Create and publish a release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      prerelease:
        type: boolean
        default: false
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
      
jobs:
  example:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.inputs.version }}
